ver 1
Oligarhselmasha/java-shareit pull request #1
Opened 2023-03-19 18:19 UTC by Oligarhselmasha

2023-03-20 16:10 UTC, afomkina requested changes

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/errorsHandling/ErrorHandler.java
> +public class ErrorHandler {
🔥

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/errorsHandling/ErrorResponse.java
> +@Data
Лучше генерировать только нужные из функций, чтобы не загружать программу ненужными генерациями. Предлагаю оставить из даты только нужные для данного объекта аннотации

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") Integer userId,
Лучше вынести повторяющийся хэдер в константу, а лучше сразу в отдельный класс `Variables`, так как он нам еще понадобится в других классах

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                      @RequestParam(required = true) String text) {
Поля, помеченные аннотацией `@RequestParam` по умолчанию == true, поэтому явно объявлять `required = true` не нужно. Лучше удалить

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapperImpl.java
> +    private final ItemRepository itemRepository;
Лишний инжект. Нигде ниже не используется, нужно удалить

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    ItemDto toItemDto(Item item);
Метод нигде не используется

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapperImpl.java
> +public class ItemMapperImpl implements ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-03-20 16:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapperImpl.java
> +@Data
Лишняя, нужно удалить
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-03-20 16:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final List<Item> items = new ArrayList<>();
Для ускорения работы лучше воспользоваться [HashMap](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html)

2023-03-20 16:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    UserDto toUserDto(User user);
Нигде не используется

2023-03-20 16:10 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final List<User> users = new ArrayList<>();
Лучше `HashMap`

2023-03-20 16:58 UTC, Oligarhselmasha commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +import org.springframework.web.bind.annotation.*;
Поправил, получилось аж 10 импортов. `Ctrl + Alt + O` всегда прогоняю, тут эта команда не сработала, видимо посчитала, что будет красивее со *, чем с 10 импортами)

2023-03-21 15:49 UTC, AnastasiyaFomkina approved these changes
Работу принимаю, оставила два маленьких комментария, поправь, пожалуйста, прежде, чем мерджить :)


Рада, что удалось прикрутить мапстракт и починить тесты

2023-03-21 15:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
Лучше обозначать интерфейс, а уже инициализировать объект с определенной реализацией. Так программа становится более гибкой и не сломается, если нужно будет подменить реализацию на другую

2023-03-21 15:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
И здесь

2023-03-21 15:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
Map<Integer, Item> items = new HashMap<>()
```suggestion
    private final Map<Integer, Item> items = new HashMap<>();
```

2023-03-22 05:32 UTC, merged