Add item requests
Oligarhselmasha/java-shareit pull request #3
Opened 2023-06-04 12:06 UTC by Oligarhselmasha

2023-06-09 12:55 UTC, AnastasiyaFomkina requested changes

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @RequestParam(defaultValue = "null", required = false) String from,
Нужно заменить строку на число, чтобы не возникало проблем при парсинге.
Соответственно, можно будет поставить адекватное дефотлное значение, а не `null` и провалидировать поля, что они не меньше 0

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (fromInt < 0 || sizeInt <= 0) {
Можно сделать с помощью аннотаций валидации

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public List<Booking> getBookings(@RequestHeader(USER_HEADER) Integer userId, @RequestParam(defaultValue = "ALL",
Нужно переделать методы контролеров так, чтобы они возвращали Dto-объект, а не сущность из базы

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : items) {
Нужно переписать с помощью forEach() или stream api

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        items.forEach(i -> itemDtos.add(toItemDto(i)));
Лучше использовать `stream.map`, а потом собирать в список с помощью `.collect(Collectors.toList())`

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                comment.setItem(itemRepository.findById(itemId).orElseThrow());
Лучше вынести создание `Comment` в отдельный приватный метод, чтобы разгрузить большой метод `createItemsComment`

2023-06-09 12:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private ItemDto toItemDto(Item item) {
Лучше вынести в маппер

2023-06-09 12:55 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +        for (Request request : requests) {
Нужно переписать цикл с помощью stream api

2023-06-09 12:55 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +            for (Item requestsItem : requestsItems) {
Нужно переписать цикл с помощью stream api

2023-06-09 12:55 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public UserDto() {
`@NoArgsContructor`

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/errorsHandling/ErrorHandlerTest.java
> +    void handleIValidationException() {
Тесты ради покрытие - `code smell`. Нужно проверить, что мы получаем корректные ошибки в интеграционных или юнит тестах, а этот класс нужно будет удалить

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 1)
Нужно использовать константу `USER_HEADER`.
Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                        .header("X-Sharer-User-Id", 1)
Нужно использовать константу `USER_HEADER`.

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +        User user = userService.createUser(new UserDto("Кирилл", "kirill-bulanov@yandex.ru"));
Нужно вынести в `@BeforeEach`, так как повторяется во всех тестах ниже

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void createItem() {
Предлагаю немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +                        .header("X-Sharer-User-Id", 1)
Нужно заменить на константу

2023-06-09 12:55 UTC, afomkina commented on src/test/java/ru/practicum/shareit/user/mapper/UsersMapperTest.java
> +//
Нужно удалить

2023-06-12 12:06 UTC, Oligarhselmasha commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        items.forEach(i -> itemDtos.add(toItemDto(i)));
Прости, пожалуйста, но не понял этого замечания

2023-06-12 18:18 UTC, Oligarhselmasha commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    void createItem() {
С твоего позволения я позже это внедрю, сроки очень поджимают

2023-06-13 06:03 UTC, AnastasiyaFomkina approved these changes

2023-06-17 07:49 UTC, merged